language: node_js
cache: yarn
jobs:
  include:
    - stage: test
      script: yarn test-single && codecov
    - stage: npm-bundle
      script: yarn build && npm version $TRAVIS_BRANCH --allow-same-version --allow-empty
      deploy:
        edge: true
        provider: npm
        email: bameyrick@gmail.com
        api_token:
          secure: PKhyI8uoPcefBsLW4znvxRb/Rv2MQppQOu5sVbKgPg01PGq0OehZw4f1hea70XSokAYQOEq9utks7b91SFgRL3ubP76VloM0tE7OBWKpGkKIWyR8Gzob14lmhmGntqyU0SB8LZ9F0T0nYHsCwonyBNr8F3by0DkG6KKSUSigRe4eSOH3qOboyId11ua4pvoiNv+SpGzR7MvHFhpJXvCgny7fmqpOA88TPPLXWHCiXojQ1XfY6IA8d0yrgLcau3cke0/5YMMDPgt+PXVOGnbc8r0RqzcxQ30hOug8ohpnUtI/VLPgzD2R8IB5A/swvnmxDd8oUGLP3cibYZ/180ebcAayOaI79ImvYta17AWx0GbWpKXZlMl3boEWehfSgafZFcF2ZHURUflOTMwQ1JW6z9O6NzsQUvt2vCn0cx6HFzANDNC2WfkwYVMq8YZieQrgoBTTPGt0KjYlI3n3LlVO5epUunIszIgZdIM3F1lnP3/k5pvklkJLic1ZOu7v42Z50Q1Kb03LyksZDWo8C4LGoaYrDO8Lv7+yuNcuH+kgkuFSh1cIw/L0b5NyeoDWkTeI5MeAddROa4gHkEa8xlQs8gMRXQ22LNrti6bSj5TxOYr3RhyQqA8K7385mN61l5GnVxLY7uQIQRY1ItVIEm78gBt9GbNyneWlyJlHVM3DjGY=
        on:
          tags: true
stages:
  - name: test
    if: tag IS NOT present
  - name: npm-bundle
    if: tag IS present
